bbs/urls.py
from django.urls import path
from bbs.views import views
from bbs.views import data_views


app_name = 'bbs'
urlpatterns = [
    path('', views.KeijibanView.as_view(), name='list'),
    path('list/', views.KeijibanView.as_view(), name='list'),
    path('bbs/expand/<int:pk>', views.expandView, name='file_expand'),
    # ファイル登録・修正
    path('bbs/list/', data_views.FileListView.as_view(), name='file_list'),
    path('bbs/create/', data_views.FileCreateView.as_view(), name='file_create'),
    path('bbs/update/<int:pk>', data_views.FileUpdateView.as_view(), name='file_update'),
    path('bbs/delete/<int:pk>', data_views.FileDeleteView.as_view(), name='file_delete'),
    path('bbs/rotate/<int:pk> <int:direc>', data_views.FileRotateView.as_view(), name='file_rotate'),
]

keijiban/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bbs.urls')),
    # path('keijiban/', include('bbs.urls')),
    path('register/', include('register.urls')),
]

# 開発環境で静的ファイルをアップロードするための追加設定。
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

register/urls.py
from django.urls import path
from register.views import views
from register.views import user_operator


"""
https://torina.top/detail/222/
"""
app_name = 'register'
urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    # ユーザー登録・修正
    path('signup/', user_operator.TempUserCreateView.as_view(), name='signup'),
    path('signup_done/', user_operator.TempUserDoneView.as_view(), name='temp_user_done'),
    path('user_list/', user_operator.UserListView.as_view(), name='user_list'),
    path('user_update/<int:pk>/', user_operator.UserManagementView.as_view(), name='user_update'),
    path('pwd_update/<int:pk>/', user_operator.UserPasswordUpdate.as_view(), name='pwd_update'),
    # ユーザー削除
    path('delete_user/<int:pk>', user_operator.DeleteUserView.as_view(), name='delete_user'),
]

bbs/models.py
import os
from io import BytesIO

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.files.base import ContentFile
from django.db import models
from django.utils import timezone
from PIL import Image

user = get_user_model()


def get_upload_to(instance, filename):
    """upload_toを動的(カテゴリのpath毎)に指定する
    https://docs.djangoproject.com/ja/4.0/ref/models/fields/
    ここで、ファイルをuploadするパスを設定する。
    settings.pyで設定したMEDIA_ROOT + IMAGE_PATH + filenameとなる。
    """
    try:
        path = os.path.join(settings.IMAGE_PATH, filename)
    except Exception as e:
        _ = e
        path = os.path.join("default", filename)
    return path


def image_size(value):
    """アップロード写真のサイズを制限"""
    limit_kb = settings.LIMMIT_IMAGE_SIZE
    if value.size > limit_kb * 1024:
        raise ValidationError(f"ファイルサイズは {limit_kb}KB 以下にしてください。")
    # if value.size > limit:
    #     mb = limit / 1024 / 1024
    #     raise ValidationError(f"ファイルサイズは {mb}MB 以下にしてください。")


def remove_exif(image_field):
    """exifデータを削除する"""
    image = Image.open(image_field)

    # 画像データを取得
    data = list(image.getdata())
    image_without_exif = Image.new(image.mode, image.size)
    image_without_exif.putdata(data)

    # バッファに新しい画像を保存
    buffer = BytesIO()
    image_without_exif.save(buffer, format=image.format)
    buffer.seek(0)

    # ContentFileに変換して新しいファイルを作成
    return ContentFile(buffer.read())


class File(models.Model):
    """アップロードするイメージファイル"""

    title = models.CharField(verbose_name="タイトル", max_length=32)
    summary = models.CharField(verbose_name="概要", max_length=128, blank=True, null=True)
    img = models.ImageField(
        verbose_name="写真ファイル", upload_to=get_upload_to, validators=[image_size], null=True, blank=False
    )
    rank = models.IntegerField(verbose_name="表示順", default=0)
    user = models.ForeignKey(user, verbose_name="名前", on_delete=models.CASCADE)
    created_at = models.DateTimeField(verbose_name="作成日", default=timezone.now)
    alive = models.BooleanField(verbose_name="有効", default=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """exifデータ消去"""
        if self.img:
            # EXIFデータを削除した画像を取得
            new_image = remove_exif(self.img)

            # 画像フィールドを新しいファイルに置き換える
            self.img.save(self.img.name, new_image, save=False)

        # 通常の保存を実行
        super().save(*args, **kwargs)

register/models.py
from django.contrib.auth.models import AbstractUser, Group
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.dispatch import receiver
# from django.http import Http404


class User(AbstractUser):
    """ デフォルトのUserを少し拡張してみる。
    管理画面でパスワード変更した時の日時を持たせる。
    パスワードを定期的に変更させる場合に使う。
    """
    update_password_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.username

    def check_pw_date(self):
        return self.update_password_date


@receiver(models.signals.post_save, sender=User)
def post_save_user_signal_handler(sender, instance, created, **kwargs):
    """ シグナルによってUserにgroupを追加する。
    https://stackoverflow.com/questions/51974276/how-to-automatically-add-group-and-staff-permissions-when-user-is-created/51975193
    """
    if created:
        try:
            group = Group.objects.get(name='guest')
        except ObjectDoesNotExist:
            instance.save()
        else:
            instance.groups.add(group)
            instance.save()

bbs/forms.py
from django import forms

from bbs.models import File

CSS_CHOICES = (
    ("contain", "全体表示"),
    ("cover", "等サイズ"),
)


class FileForm(forms.ModelForm):
    """
    (1) 不要な画像ファイルは削除することとして、alive要素は封印する。
    (2) 表示順は新しい画像優先とするため、rank要素は封印する。
    ModelForm限定の方法としてclass Metaでwidgetを設定する。class以外も変更できる。
    """

    class Meta:
        model = File
        fields = ("title", "summary", "img", "created_at")
        # field毎に異なるclassを設定する場合には、この方法を取る。
        widgets = {
            "title": forms.TextInput(
                attrs={
                    "class": "input",
                }
            ),
            "summary": forms.TextInput(
                attrs={
                    "class": "input",
                }
            ),
            "img": forms.FileInput(
                attrs={
                    "class": "input",
                }
            ),
            "created_at": forms.DateTimeInput(
                attrs={
                    "class": "input",
                }
            ),
            # 'alive': forms.NullBooleanSelect(attrs={
            #     'class': "select-css",
            # }),
            # 'rank': forms.TextInput(attrs={
            #     'class': "input",
            # }),
        }
        help_texts = {"img": "※ 写真ファイルサイズは1000KB以下です"}


class SwitchCSSForm(forms.Form):
    """掲示板のcssを切り替えるためのform"""

    css = forms.ChoiceField(
        label="CSS",
        widget=forms.Select(attrs={"class": "select-css"}),
        choices=CSS_CHOICES,
        required=True,
    )

bbs/views.py
from django.views import generic
from django.contrib.auth.mixins import PermissionRequiredMixin
from library.forms import FileForm
from library.models import File
from django.urls import reverse_lazy


class FileCreateView(PermissionRequiredMixin, generic.CreateView):
    """ 管理者用 ファイルの作成. """
    model = File
    form_class = FileForm
    # 必要な権限
    permission_required = ("bbs.add_file")
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True
    success_url = reverse_lazy('bbs:file_index')


class FileUpdateView(PermissionRequiredMixin, generic.UpdateView):
    """ 管理者用 ファイルの更新. """
    model = File
    form_class = FileForm
    # 必要な権限
    permission_required = ("bbs.add_file")
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True
    success_url = reverse_lazy('bbs:file_index')


class FileDeleteView(PermissionRequiredMixin, generic.DeleteView):
    """ 管理者用 ファイルの削除. """
    template_name = 'bbs/file_confirm_delete.html'
    model = File
    # 必要な権限
    permission_required = ("bbs.add_file")
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True
    success_url = reverse_lazy('bbs:file_index')

bbs/views/data_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views import generic
from PIL import Image

from bbs.forms import FileForm
from bbs.models import File


class FileCreateView(PermissionRequiredMixin, generic.CreateView):
    """管理者用 ファイルの作成."""

    model = File
    form_class = FileForm
    # 必要な権限
    permission_required = "bbs.add_file"
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True
    success_url = reverse_lazy("bbs:file_list")

    def form_valid(self, form):
        # commitを停止する。
        self.object = form.save(commit=False)
        # userをセット。
        self.object.user = self.request.user
        # データを保存。
        self.object.save()
        return super().form_valid(form)


class FileUpdateView(PermissionRequiredMixin, generic.UpdateView):
    """管理者用 ファイルの更新."""

    model = File
    form_class = FileForm
    # 必要な権限
    permission_required = "bbs.add_file"
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True
    success_url = reverse_lazy("bbs:file_list")

    def form_valid(self, form):
        # commitを停止する。
        self.object = form.save(commit=False)
        # userをセット。
        self.object.user = self.request.user
        # データを保存。
        self.object.save()
        return super().form_valid(form)


class FileDeleteView(PermissionRequiredMixin, generic.DeleteView):
    """管理者用 ファイルの削除."""

    template_name = "bbs/file_confirm_delete.html"
    model = File
    # 必要な権限
    permission_required = "bbs.add_file"
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True
    success_url = reverse_lazy("bbs:file_list")


class FileListView(PermissionRequiredMixin, generic.ListView):
    """管理者用の画像list一覧"""

    model = File
    template_name = "bbs/management_list.html"
    permission_required = "bbs.add_file"

    def get_queryset(self, **kwargs):
        qs = super().get_queryset(**kwargs)
        qs = qs.order_by("-created_at")
        return qs


class FileRotateView(PermissionRequiredMixin, generic.TemplateView):
    """写真の回転処理
    iPhoneで写真が横向きになるため、修正の処理。
    イメージを読み込んで、時計回りに90度回転して保存する。
    https://docs.djangoproject.com/ja/4.0/topics/files/
    """

    permission_required = "bbs.add_file"
    template_name = "bbs/file_rotate.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs["pk"]
        direc = self.kwargs["direc"]
        # imageをpillowで読み込み、回転、保存する。
        qs = File.objects.get(pk=pk)
        img_path = qs.img.path
        img = Image.open(img_path)
        if direc == 1:
            img_rotate = img.rotate(270, expand=True)
        elif direc == 0:
            img_rotate = img.rotate(90, expand=True)
        img_rotate.save(img_path)
        # ToDo: 画像の回転処理が反映されない画像が表示される。
        qs = File.objects.get(pk=pk)
        context["img"] = qs.img.url
        return context

bbs/views/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models.aggregates import Max
from django.shortcuts import render
from django.views import generic

from bbs.forms import SwitchCSSForm
from bbs.models import File


# class KeijibanView(PermissionRequiredMixin, generic.TemplateView):
class KeijibanView(generic.TemplateView):
    """掲示板表示"""

    model = File
    template_name = "bbs/keijiban.html"
    # permission_required = "bbs.view_file"

    def get_template_names(self):
        """UAmiddlewareクラスによりtemplateファイルを切り替える"""
        if self.request.user_agent_flag == "mobile":
            template_name = "bbs/keijiban_mobile.html"
        else:
            template_name = "bbs/keijiban_pc.html"
        # if self.request.user.is_superuser:
        #     template_name = 'bbs/template_superuser.html'
        # elif self.request.user.is_authenticated:
        #     template_name = 'bbs/template_authenticated.html'
        # else:
        #     template_name = self.template_name
        return [template_name]

    def get_context_data(self, **kwargs):
        """有効な画像を表示する"""
        context = super().get_context_data(**kwargs)
        css = self.request.GET.get("css", "contain")
        qs = File.objects.filter(alive=True).order_by("-created_at")
        max_date = File.objects.filter(alive=True).aggregate(Max("created_at"))

        # formフィールドに初期値を設定。
        selectcssform = SwitchCSSForm(
            initial={
                "css": css,
            }
        )
        # 最新の画像データ登録日をタイトル表示させる。
        context["title"] = max_date["created_at__max"]
        context["file_list"] = qs
        context["form"] = selectcssform
        context["css"] = css
        return context


def expandView(request, pk):
    """拡大イメージを表示
    非常にシンプルなので、関数としてみる。
    """
    img_obj = File.objects.get(pk=pk)
    context = {"img_obj": img_obj}
    return render(request, "bbs/file_expand.html", context)

bbs/templates/bbs/file_confirm_delete.html
{% extends "base.html" %}

<!-- navbar -->
{% block navbar %}
<nav class="navbar is-fixed-top is-black is-size-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">ファイル管理</a>
    {# ハンバーガアイコンのため以下の5行とbase.htmlでのjsスクリプトが必要 #}
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarMypage">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarMypage" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="{% url 'bbs:list' %}">掲示板</a>
      <a class="navbar-item" href="{% url 'bbs:file_list' %}">ファイル一覧</a>
    </div>
  </div>
</nav>
{% endblock navbar %}

{% block content %}
<div class="container">
  <br>
  <div class="content has-text-centered has-text-danger is-size-4">
    以下の画像を削除しますか？
  </div>
  <form action="" method="POST" enctype='multipart/form-data'>
    <div class="content has-text-centered">
      <p>{{file.title}}</p>
      {% if file.img %}
        <p><img src="{{file.img.url}}" style="width: 300px; auto;"></p>
      {% endif %}
      <br>
      <button type="submit" class="button is-danger">削除する</button>
      <a class="button is-link" href="javascript:void(0);" onclick="window.history.back();">戻る</a>
    </div>
    {% csrf_token %}
  </form>
  <br>
</div>
{% endblock %}

bbs/templates/bbs/file_list.html
{% extends "base.html" %}

{% block title %}
  管理用掲示板
{% endblock %}
<!-- navbar -->
{% block navbar %}
<nav class="navbar is-fixed-top is-black is-size-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    {# ハンバーガアイコンのため以下の5行とbase.htmlでのjsスクリプトが必要 #}
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarMypage">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarMypage" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="{% url 'bbs:list' %}">掲示板へ戻る</a>
    </div>
    <div class="navbar-end">
      <a class="navbar-item" href="{% url 'bbs:file_create' %}" >掲示写真登録</a>
      <a class="navbar-item" href="{% url 'register:pwd_update' user.pk %}" >パスワード変更</a>
      {% if perms.register.add_user %}
        <a class="navbar-item" href="{% url 'register:user_list' %}">ユーザ管理</a>
      {% endif %}
      <a class="navbar-item" href="{% url 'register:logout' %}">ログアウト</a>
    </div>
  </div>
</nav>
{% endblock navbar %}

{% block content %}
<div class="container is-fluid">
  <br>
  <div class="content has-text-centered">
    <h3>掲示板一覧</h3>
  </div>
  <br>
  {% comment %} <table class="table table_center_nowrap is-narrow is-striped"> {% endcomment %}
  <table class="table table_center is-narrow is-striped">
    <thead>
      <tr>
        {% comment %} <th class="has-text-centered">タイトル</th> {% endcomment %}
        <th class="has-text-centered">画像</th>
        <th class="has-text-centered">処理</th>
      </tr>
    </thead>
    <tbody>
      {% for file in file_list %}
      <tr>
        {% comment %} <td class="has-text-left">{{file.title}}</td> {% endcomment %}
        <td class="has-text-centered">
          <img src="{{file.img.url}}" style="width: 200px; auto;">
        </td>
        {% comment %} <td class="nowrap"> {% endcomment %}
        <td>
          <a href="{% url 'bbs:file_update' file.pk %}" class="button has-background-grey-lighter is-small">
            更新
          </a>
          <a href="{% url 'bbs:file_delete' file.pk %}" class="button has-background-grey-lighter is-small">
            削除
          </a>
          <a href="{% url 'bbs:file_rotate' file.pk 0 %}" class="button has-background-grey-lighter is-small">
            左回転
          </a>
          <a href="{% url 'bbs:file_rotate' file.pk 1 %}" class="button has-background-grey-lighter is-small">
            右回転
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <br>
</div>
{% endblock %}

bbs/templates/bbs/keijiban.html
{% extends "base.html" %}
{% comment %} {% load static %} {% endcomment %}

{% block title %}
  掲示板
{% endblock %}

{% block head %}
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Cache-Control" content="no-cache">
<meta http-equiv="Expires" content="0">
{% comment %} <script src="{% static 'bbs/reload.js' %}"></script> {% endcomment %}
{% endblock %}

<!-- navbar -->
{% block navbar %}
<nav class="navbar is-fixed-top is-black" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    {% comment %} <a class="navbar-item">【掲示板】</a> {% endcomment %}
    {# ハンバーガアイコンのため以下の5行とbase.htmlでのjsスクリプトが必要 #}
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarMypage">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarMypage" class="navbar-menu">
    <div class="navbar-start">
    </div>
    <div class="navbar-end">
      {% if user.is_anonymous %}
        <a class="navbar-item" href="{% url 'register:login' %}">管理者ログイン</a>
      {% else %}
        <a class="navbar-item" href="{% url 'bbs:file_list' %}">管理画面</a>
        <a class="navbar-item" href="{% url 'register:logout' %}">ログアウト</a>
      {% endif %}
    </div>
  </div>
</nav>
{% endblock navbar %}

{% block content %}
{% comment %} <div class="container with_mobile"> {% endcomment %}
<div class="container is-fluid">
  <br>
  <div class="content has-text-centered">
    <h3>掲示板 ({{title|date}})</h3>
    <br>
    {% for file in file_list %}
      <a href="{% url 'bbs:file_expand' file.pk %}"><img src="{{file.img.url}}" style="width: 300px; auto;"></a>
    {% endfor %}
    <br>
  </div>
</div>
{% endblock %}

bbs/templates/bbs/keijiban_mobile.html
{% extends "base.html" %}
{% comment %} {% load static %} {% endcomment %}

{% block title %}
  掲示板
{% endblock %}

{% block head %}
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Cache-Control" content="no-cache">
<meta http-equiv="Expires" content="0">
{% comment %} <script src="{% static 'bbs/reload.js' %}"></script> {% endcomment %}
{% endblock %}

{% block navbar %}
<nav class="navbar is-fixed-top is-black" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarMypage">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarMypage" class="navbar-menu">
    <div class="navbar-start">
    </div>
    <div class="navbar-end">
      {% if user.is_anonymous %}
        <a class="navbar-item" href="{% url 'register:login' %}">管理者ログイン</a>
      {% else %}
        <a class="navbar-item" href="{% url 'bbs:file_list' %}">管理画面</a>
        <form method="post" class="navbar-item" action="{% url 'register:logout' %}">
          {% csrf_token %}
          <button type="submit">ログアウト</button>
        </form>
      {% endif %}
    </div>
  </div>
</nav>
{% endblock navbar %}

{% block content %}
<div class="container">
  <br>
  <div class="content has-text-centered">
    <h4>掲示板 ({{title|date}})</h4>
    <br>
    <div class="columns">
      <div class="column">
        {% for file in file_list %}
          <a href="{% url 'bbs:file_expand' file.pk %}"><img src="{{file.img.url}}" style="width: 95%; auto;"></a>
        {% endfor %}
      </div>
    </div>
    <br>
  </div>
</div>
{% endblock %}

bbs/templates/bbs/keijiban_pc.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  掲示板
{% endblock %}

{% block head %}
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Cache-Control" content="no-cache">
<meta http-equiv="Expires" content="0">
{% comment %} <script src="{% static 'bbs/reload.js' %}"></script> {% endcomment %}
<link href="{% static 'bbs/img.css' %}" rel="stylesheet">
{% endblock %}

<!-- navbar -->
{% block navbar %}
<nav class="navbar is-fixed-top is-black" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">【SG】</a>
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarMypage">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarMypage" class="navbar-menu">
    <div class="navbar-start">
      <form class="navbar-item" action="" method="get">
        {{form.css}}
        <button type="submit" class="button is-link is-size-7">切替</button>
      </form>
    </div>
    <div class="navbar-end">
      {% if user.is_anonymous %}
        <a class="navbar-item" href="{% url 'register:login' %}">管理者ログイン</a>
      {% else %}
        <a class="navbar-item" href="{% url 'bbs:file_list' %}">管理画面</a>
        <form method="post" class="navbar-item" action="{% url 'register:logout' %}">
          {% csrf_token %}
          <button type="submit">ログアウト</button>
        </form>
      {% endif %}
    </div>
  </div>
</nav>
{% endblock navbar %}

{% block content %}
{% comment %} <div class="container with_mobile"> {% endcomment %}
<div class="container is-fluid">
  <br>
  <div class="content has-text-centered">
    <h3>掲示板 ({{title|date}})</h3>
    <br>
    {% for file in file_list %}
      {% if file.img %}
        <a href="{% url 'bbs:file_expand' file.pk %}">
          <img class="{{css}}" src="{{file.img.url}}" style="width: 300px; auto;">
        </a>
      {% endif %}
    {% endfor %}
    <br>
  </div>
</div>
{% endblock %}

bbs/templates/bbs/management_list.html
{% extends "base.html" %}

{% block title %}
  管理用掲示板
{% endblock %}
<!-- navbar -->
{% block navbar %}
<nav class="navbar is-fixed-top is-black is-size-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    {# ハンバーガアイコンのため以下の5行とbase.htmlでのjsスクリプトが必要 #}
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarMypage">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarMypage" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="{% url 'bbs:list' %}">掲示板へ戻る</a>
    </div>
    <div class="navbar-end">
      <a class="navbar-item" href="{% url 'bbs:file_create' %}" >掲示写真登録</a>
      <a class="navbar-item" href="{% url 'register:pwd_update' user.pk %}" >パスワード変更</a>
      {% if perms.register.add_user %}
        <a class="navbar-item" href="{% url 'register:user_list' %}">ユーザ管理</a>
      {% endif %}
      <form method="post" class="navbar-item" action="{% url 'register:logout' %}">
        {% csrf_token %}
        <button type="submit">ログアウト</button>
      </form>
    </div>
  </div>
</nav>
{% endblock navbar %}

{% block content %}
<div class="container is-fluid">
  <br>
  <div class="content has-text-centered">
    <h3>管理者用リスト</h3>
    <p>回転処理後は再読み込みをしてください（キャッシュのため）</p>
  </div>
  <br>
  {% comment %} <table class="table table_center_nowrap is-narrow is-striped"> {% endcomment %}
  <table class="table table_center is-narrow is-striped">
    <thead>
      <tr>
        {% comment %} <th class="has-text-centered">タイトル</th> {% endcomment %}
        <th class="has-text-centered">画像</th>
        <th class="has-text-centered">処理</th>
      </tr>
    </thead>
    <tbody>
      {% for file in file_list %}
      <tr>
        {% comment %} <td class="has-text-left">{{file.title}}</td> {% endcomment %}
        <td class="has-text-centered">
          {% if file.img %}
            <img src="{{file.img.url}}" style="width: 200px; auto;">
          {% endif %}
        </td>
        {% comment %} <td class="nowrap"> {% endcomment %}
        <td>
          <a href="{% url 'bbs:file_update' file.pk %}" class="button has-background-grey-lighter is-small">
            更新
          </a>
          <a href="{% url 'bbs:file_delete' file.pk %}" class="button has-background-grey-lighter is-small">
            削除
          </a>
          <a href="{% url 'bbs:file_rotate' file.pk 0 %}" class="button has-background-grey-lighter is-small">
            左回転
          </a>
          <a href="{% url 'bbs:file_rotate' file.pk 1 %}" class="button has-background-grey-lighter is-small">
            右回転
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <br>
</div>
{% endblock %}