bbs/urls.py
from django.urls import path
from bbs.views import views
from bbs.views import data_views


app_name = 'bbs'
urlpatterns = [
    path('', views.KeijibanView.as_view(), name='list'),
    path('list/', views.KeijibanView.as_view(), name='list'),
    path('bbs/expand/<int:pk>', views.expandView, name='file_expand'),
    # ファイル登録・修正
    path('bbs/list/', data_views.FileListView.as_view(), name='file_list'),
    path('bbs/create/', data_views.FileCreateView.as_view(), name='file_create'),
    path('bbs/update/<int:pk>', data_views.FileUpdateView.as_view(), name='file_update'),
    path('bbs/delete/<int:pk>', data_views.FileDeleteView.as_view(), name='file_delete'),
    path('bbs/rotate/<int:pk> <int:direc>', data_views.FileRotateView.as_view(), name='file_rotate'),
]

keijiban/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bbs.urls')),
    # path('keijiban/', include('bbs.urls')),
    path('register/', include('register.urls')),
]

# 開発環境で静的ファイルをアップロードするための追加設定。
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

register/urls.py
from django.urls import path
from register.views import views
from register.views import user_operator


"""
https://torina.top/detail/222/
"""
app_name = 'register'
urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    # ユーザー登録・修正
    path('signup/', user_operator.TempUserCreateView.as_view(), name='signup'),
    path('signup_done/', user_operator.TempUserDoneView.as_view(), name='temp_user_done'),
    path('user_list/', user_operator.UserListView.as_view(), name='user_list'),
    path('user_update/<int:pk>/', user_operator.UserManagementView.as_view(), name='user_update'),
    path('pwd_update/<int:pk>/', user_operator.UserPasswordUpdate.as_view(), name='pwd_update'),
    # ユーザー削除
    path('delete_user/<int:pk>', user_operator.DeleteUserView.as_view(), name='delete_user'),
]

register/models.py
from django.contrib.auth.models import AbstractUser, Group
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.dispatch import receiver
# from django.http import Http404


class User(AbstractUser):
    """ デフォルトのUserを少し拡張してみる。
    管理画面でパスワード変更した時の日時を持たせる。
    パスワードを定期的に変更させる場合に使う。
    """
    update_password_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.username

    def check_pw_date(self):
        return self.update_password_date


@receiver(models.signals.post_save, sender=User)
def post_save_user_signal_handler(sender, instance, created, **kwargs):
    """ シグナルによってUserにgroupを追加する。
    https://stackoverflow.com/questions/51974276/how-to-automatically-add-group-and-staff-permissions-when-user-is-created/51975193
    """
    if created:
        try:
            group = Group.objects.get(name='guest')
        except ObjectDoesNotExist:
            instance.save()
        else:
            instance.groups.add(group)
            instance.save()

register/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (AuthenticationForm, PasswordChangeForm,
                                       UserCreationForm)
from django.contrib.auth.models import Group

User = get_user_model()


class LoginForm(AuthenticationForm):
    """ログインフォーム"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'input'
            field.widget.attrs['placeholder'] = field.label


class TempUserCreateForm(UserCreationForm):
    """ ユーザー仮登録用フォーム
    emailを必須フィールドにするため、UserCreationFormを継承する。
    元々はusername、password1、確認用のpassword2の3つだけど、emailを必須とする。
    https://docs.djangoproject.com/ja/3.2/topics/auth/default/
    """
    username = forms.CharField(label='ユーザ名', help_text='* 部屋番号が分かる名前にしてください。')
    email = forms.EmailField(label='Eメールアドレス', required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "input"


class UserUpdateForm(forms.ModelForm):
    """ 管理者が仮ユーザーのis_activeフラグを更新するフォーム """
    group = forms.ModelChoiceField(
        empty_label='Group選択',
        # queryset=Group.objects.all().exclude(name='director'),
        queryset=Group.objects.all(),
        required=True,
        widget=forms.Select(attrs={'class': 'select-css'})
        )

    class Meta:
        model = User
        fields = ('username', 'email', 'is_active')
        labels = {
            'username': 'ユーザ名',
            'is_active': '有効',
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'input'}),
            'email': forms.EmailInput(attrs={'class': 'input'}),
            'is_active': forms.NullBooleanSelect(attrs={'class': 'select-css'})
        }


class PasswordUpdateForm(PasswordChangeForm):
    """ ユーザーが自分のパスワードを更新するためのフォーム """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "input"

register/views/user_operator.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import PasswordChangeView
from django.views import generic
from django.contrib.auth.models import Group
from django.shortcuts import redirect, resolve_url
from django.urls import reverse_lazy

from register.forms import (PasswordUpdateForm, TempUserCreateForm, UserUpdateForm)


User = get_user_model()


class UserListView(PermissionRequiredMixin, generic.ListView):
    """ 管理者が使用するユーザリストの一覧表示。
    templatesファイルはデフォルト（user_list.html）を使用。
    渡されるobjectもデフォルトの「user_list」。
    """
    model = User
    permission_required = ("register.add_user",)
    template_name = 'register/user/user_list.html'

    def get_queryset(self, **kwargs):
        qs = super().get_queryset(**kwargs).order_by('is_active')
        qs = qs.exclude(is_superuser=True).order_by('-groups', 'is_active')
        return qs


class TempUserCreateView(generic.CreateView):
    """ 未登録ユーザーが仮登録するためのVIEW。
    ユーザには「add_post」と「view_post」のパーミションを付加する。
    """
    template_name = 'register/user/temp_user_create_form.html'
    form_class = TempUserCreateForm

    def form_valid(self, form):
        """ 仮登録ではis_activeフラグを立てず、管理者が承認することで
        is_active＝Trueとする。また登録するユーザには権限を付加する。
        """
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        return redirect('register:temp_user_done')


class TempUserDoneView(generic.TemplateView):
    """ 仮登録完了後、メールを待つように表示するだけのVIEW。 """
    template_name = 'register/user/temp_user_done.html'


class OnlyYouMixin(UserPassesTestMixin):
    """ パスワードの変更処理用
    自分自身だけでなく、ユーザ登録情報によって制限することができる。
    https://qiita.com/chanyou0311/items/31a4380d11c904563c86
    https://docs.djangoproject.com/ja/3.2/topics/auth/default/
    """
    raise_exception = True

    def test_func(self):
        user = self.request.user
        # return user.pk == self.kwargs['pk'] or user.is_superuser
        return user.pk == self.kwargs['pk']


class UserPasswordUpdate(OnlyYouMixin, PasswordChangeView):
    """ ログインしたユーザが自分でパスワードを変更するためのVIEW。"""
    model = User
    form_class = PasswordUpdateForm
    template_name = 'register/user/password_update_form.html'

    def get_success_url(self):
        # return resolve_url('register:pwd_update', pk=self.kwargs['pk'])
        return resolve_url('bbs:file_list')


class UserManagementView(PermissionRequiredMixin, generic.UpdateView):
    """ 管理者がユーザの「有効性」を操作するためのVIEW。 """
    model = User
    form_class = UserUpdateForm
    template_name = 'register/user/user_update_form.html'
    permission_required = ("register.add_user",)

    def get_success_url(self):
        return resolve_url('register:user_list')

    def form_valid(self, form):
        """ 仮登録ではis_activeフラグを立てず、管理者が承認することで
        is_active＝Trueとする。またグループの変更も行う。
        """
        user = form.save(commit=False)
        user.save()
        new_group = form.cleaned_data['group']
        user.groups.clear()
        group = Group.objects.get(name=new_group)
        user.groups.add(group)
        return redirect('register:user_list')

    def get_context_data(self, **kwargs):
        """ ユーザ修正画面で現在値をformに表示させる  """
        context = super().get_context_data(**kwargs)
        pk = self.object.pk
        user = User.objects.get(pk=pk)
        groups = user.groups.all()
        if groups.exists():
            group_name = groups[0]
        else:
            group_name = ''

        user_update_form = UserUpdateForm(initial={
            'username': user.username,
            'email': user.email,
            'is_active': user.is_active,
            'group': group_name
        })
        context['form'] = user_update_form
        return context


class DeleteUserView(PermissionRequiredMixin, generic.DeleteView):
    """ 削除View """
    model = User
    template_name = 'register/user/user_confirm_delete.html'
    # 削除が成功した場合に遷移するurl
    success_url = reverse_lazy('register:user_list')
    # # 削除してよいか確認するためのtemplate
    # template_name = "register/user/user_confirm_delete.html"
    # 必要な権限（データ登録できる権限は共通）
    permission_required = ("register.add_user",)
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True

register/views/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView

from register.forms import LoginForm
# from django.contrib.auth.models import Permission


User = get_user_model()


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'register/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = 'register/logout.html'

register/templates/register/user/password_update_form.html
{% extends "base.html" %}
{% block content %}
<div class="container is-fluid ">
  <br>
  <div class="content has-text-centered">
    <h3>{{user.username}}</h3>
  </div>
  <br>
  <form method='POST' enctype='multipart/form-data' id="form_style">
    {{ form.non_field_errors }}
    {% for field in form %}
      <div class='field'>
        <div class='control'>
          <div class='label'>{{ field.label_tag }}</div>
          {% if field.help_text %}
            <span class='helptext'>{{ field.help_text }}</span>
          {% endif %}
          <div class='my_field'>{{ field }}</div>
          {{ field.errors }}
        </div>
      </div>
    {% endfor %}
    {% csrf_token %}
    <br>
    <div class='my_button has-text-centered'>
      <button type='submit' class='button is-link'>送信</button>
      <a class="button is-dark" href="{% url 'bbs:file_list' %}">戻る</a>
    </div>
  </form>
{% comment %} 
    <form action="" method="POST">
      {{ form.non_field_errors }}
      {% csrf_token %}
      <table class="table">
        {{form}}
      </table>
      <br>
      <button type="submit" class="button is-primary">送信</button>
      <a class="button is-dark" href="{% url 'bbs:file_list' %}">戻る</a>
    </form> {% endcomment %}

</div>
{% endblock %}

register/templates/register/user/temp_user_create_form.html
{% extends "base.html" %}
{% block content %}
<div class="container is-fluid ">
  <br>
  <div class="content has-text-centered">
    <p>
    ここはソフィア・ガーデンズ川崎管理組合の委員会メンバー専用です。<br>
    仮登録した後、認証して本登録となります。本登録完了したらメールでお知らせします。
    <hr>
    </p>
  </div>
  <form method='POST' enctype='multipart/form-data' id="form_style">
    {{ form.non_field_errors }}
    {% for field in form %}
      <div class='field'>
        <div class='control'>
          <div class='label'>{{ field.label_tag }}</div>
          <div class='my_field'>{{ field }}</div>
          {{ field.errors }}
        </div>
      </div>
    {% endfor %}
    {% csrf_token %}
    <br>
    <div class='content has-text-centered my_button'>
      <button type='submit' class='button is-link'>登録</button>
      <a class='button is-danger' href='javascript:void(0);' onclick='window.history.back();'>戻る</a>
    </div>
  </form>
</div>
{% endblock %}

register/templates/register/user/temp_user_done.html
{% extends "base.html" %}
{% load static %} {# {% staticを使うため必要 #}

{% block title %}
Accept
{% endblock title %}
{% block head %}
  <link href="{% static 'blog.css' %}" rel="stylesheet">
{% endblock head %}
{% block navbar %}
<nav class="navbar is-fixed-top is-black" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">【{{user}}】</a>
    {# ハンバーガアイコンのため #}
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarMainMenu">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarMainMenu" class="navbar-menu">
    <div class="navbar-end">
      <a class="navbar-item" href="{% url 'bbs:list' %}">掲示板</a>
    </div>
  </div>
</nav>
{% endblock navbar %}
{% block content %}
<div class="container is-fluid ">
  <div class="content has-text-centered">
    <p>仮登録しました。本登録が完了しましたらメールを送ります。</p>
  </div>
</div>
{% endblock %}

register/templates/register/user/user_confirm_delete.html
{% extends "base.html" %}

<!-- navbar -->
{% block navbar %}
<nav class="navbar is-fixed-top is-black is-size-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">ユーザ削除</a>
    {# ハンバーガアイコンのため以下の5行とbase.htmlでのjsスクリプトが必要 #}
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarMypage">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
</nav>
{% endblock navbar %}

{% block content %}
<div class="container">
  <br>
  <form action="" method="POST" enctype='multipart/form-data'>
    <div class="content has-text-centered">
      <H4>ユーザ : {{ user.username }}</H4>
      <p>削除しますか？</p>
      <br>
      <button type="submit" class="button is-danger is-size-7">削除する</button>
      <a class="button is-primary is-size-7" href="javascript:void(0);" onclick="window.history.back();">戻る</a>
    </div>
    {% csrf_token %}
  </form>
</div>
{% endblock %}

register/templates/register/user/user_list.html
{% extends "base.html" %}
{% load static %} {# {% static  を使うため必要 #}

{% block title %}
登録ユーザ 一覧
{% endblock title %}
{% block head %}
{% endblock head %}
{% block navbar %}
<nav class="navbar is-fixed-top is-black" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">【{{user}}】</a>
    {# ハンバーガアイコンのため #}
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarMainMenu">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarMainMenu" class="navbar-menu">
    <div class="navbar-start">
    </div>
    <div class="navbar-end">
      <a class="navbar-item" href="{% url 'bbs:file_list' %}">戻る</a>
    </div>
  </div>
</nav>
{% endblock navbar %}
{% block content %}
<br>
{% comment %} <div class="container with_mobile"> {% endcomment %}
<div class="container">
  <div class="content has-text-centered">
    <h4>登録ユーザ 一覧</h4>
  </div>
  <table class="table table_center_nowrap is-striped is-narrow is-responsible">
    <thead>
      <tr>
        <th class="has-text-centered">group</th>
        <th class="has-text-centered">user</th>
        <th class="has-text-centered">email</th>
        <th class="has-text-centered">状況</th>
        <th class="has-text-centered">削除</th>
      </tr>
    </thead>
    <tbody>
      {% for list in user_list %}
      <tr>
        <td class="has-text-left">{{ list.groups.get }}</td>
        <td class="has-text-left"><a href="{% url 'register:user_update' list.pk %}">{{ list.username}}</a></td>
        <td class="has-text-left">{{ list.email}}</td>
        {% if list.is_active == False %}
          <td class="has-text-centered has-text-danger">{{ list.is_active}}</td>
        {% else %}
          <td class="has-text-centered ">{{ list.is_active}}</td>
        {% endif %}
        <td class="has-text-left"><a href="{% url 'register:delete_user' list.pk %}">削除</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% include "page.html" %}
{% endblock %}

register/templates/register/user/user_update_form.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="content has-text-centered">
    <h4>登録ユーザの編集</h4>
  </div>
  <div class="content" id="form_style">
    <form method='POST' enctype='multipart/form-data' id='form_style'>
      {{ form.non_field_errors }}
      {% for field in form %}
        <div class='field'>
          <div class='control'>
            <div class='label'>{{ field.label_tag }}</div>
            <div class='my_field'>{{ field }}</div>
            {{ field.errors }}
          </div>
        </div>
      {% endfor %}
      {% csrf_token %}
      <br>
      <div class='my_button has-text-centered'>
        <button type='submit' class='button is-link'>登録</button>
        <a class="button is-danger" href="{% url 'register:user_list' %}">戻る</a>
      </div>
    </form>
  </div>
</div>
{% endblock %}